frr version 9.1
frr defaults traditional
hostname uk-lon-edge-01
log syslog informational
service integrated-vtysh-config
!
ntp server 10.200.0.1
ntp server 10.200.0.2
!
agentx
!
interface lo
 ip address 10.255.0.7/32
!
interface eth0
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20
 ip ospf bfd
 mtu 9000
!
interface eth1
 mtu 9000
!
router ospf
 ospf router-id 10.255.0.7
 passive-interface lo
!
router bgp 65007
 bgp router-id 10.200.0.22
 bgp log-neighbor-changes
 bgp graceful-restart
 no bgp ebgp-requires-policy
 neighbor 10.200.0.13 remote-as 65003
 neighbor 10.200.0.13 description uk-lon-core-01
 neighbor 10.200.0.13 timers 10 30
 neighbor 10.200.0.13 password Gesh!Bgp65003x65007
 neighbor 10.200.0.13 bfd
 neighbor 10.200.0.15 remote-as 65005
 neighbor 10.200.0.15 description us-nyc-core-01
 neighbor 10.200.0.15 timers 10 30
 neighbor 10.200.0.15 password Gesh!Bgp65005x65007
 neighbor 10.200.0.15 bfd
 !
 address-family ipv4 unicast
  network 10.70.1.0/24
  network 10.255.0.7/32
  neighbor 10.200.0.13 activate
  neighbor 10.200.0.13 soft-reconfiguration inbound
  neighbor 10.200.0.15 activate
  neighbor 10.200.0.15 soft-reconfiguration inbound
 exit-address-family
!
bfd
 peer 10.200.0.13
  receive-interval 100
  transmit-interval 100
  detect-multiplier 3
 !
 peer 10.200.0.15
  receive-interval 100
  transmit-interval 100
  detect-multiplier 3
 !
!
ip route 10.70.1.0/24 Null0
!
line vty
!
