# net-snmp agent config for us-nyc-core-01
rocommunity GESH-DC1-RO
syslocation us-nyc-core-01
syscontact gesh-noc@gesh.io
trap2sink 10.200.0.1:1162 GESH-DC1-RO
authtrapenable 1
master agentx
agentXSocket /var/agentx/master
linkUpDownNotifications yes
